default: &default
  appid: "wx7464622ccd4055fb"
  secret: "83b17bf7828203dd9557ce8ec1eb867b"
  token: "c01b187eb7e13a67775d23d082565a85"
  access_token: "/home/root/production/tree_hole/wechat_access_token"
  jsapi_ticket: "/home/root/production/tree_hole/wechat_jsapi_ticket"

production:
  appid: "wx7464622ccd4055fb"
  secret: "83b17bf7828203dd9557ce8ec1eb867b"
  token: "c01b187eb7e13a67775d23d082565a85"
  access_token: "/home/root/production/tree_hole/wechat_access_token"
  jsapi_ticket: "/home/root/production/tree_hole/wechat_jsapi_ticket"
  oauth2_cookie_duration: <%= ENV['WECHAT_OAUTH2_COOKIE_DURATION'] %> # seconds

development:
  <<: *default
  trusted_domain_fullname: "http://your_dev.proxy.qqbrowser.cc"

test:
  <<: *default
