default: &default
  corpid: "wx7464622ccd4055fb"
  corpsecret: "wx7464622ccd4055fb"
  agentid: 1
  # Or if using public account, only need above two line
  #  appid: "my_appid"
  #  secret: "my_secret"
  token: "c01b187eb7e13a67775d23d082565a85"
  access_token: "/home/root/production/tree_hole/wechat_access_token"
  encrypt_mode: false # if true must fill encoding_aes_key
  encoding_aes_key: "lcW9tXrHOIjwcg9ZzU5tM11Qc26jKAVm0HKyNntUkvk"
  jsapi_ticket: "/home/root/production/tree_hole/wechat_jsapi_ticket"

production:
  corpid: "wx7464622ccd4055fb"
  corpsecret: "wx7464622ccd4055fb"
  agentid: 1
  # Or if using public account, only need above two line
  #  appid: "my_appid"
  #  secret: "my_secret"
  token: "c01b187eb7e13a67775d23d082565a85"
  access_token: "/home/root/production/tree_hole/wechat_access_token"
  encrypt_mode: false # if true must fill encoding_aes_key
  encoding_aes_key: "lcW9tXrHOIjwcg9ZzU5tM11Qc26jKAVm0HKyNntUkvk"
  jsapi_ticket: "/home/root/production/tree_hole/wechat_jsapi_ticket"
  oauth2_cookie_duration: <%= ENV['WECHAT_OAUTH2_COOKIE_DURATION'] %> # seconds

development:
  <<: *default
  trusted_domain_fullname: "http://your_dev.proxy.qqbrowser.cc"

test:
  <<: *default
# Multiple Accounts
#
# wx2_development:
#  <<: *default
#  appid: "my_appid"
#  secret: "my_secret"
#  access_token: "tmp/wechat_access_token2"
#  jsapi_ticket: "tmp/wechat_jsapi_ticket2"
#
# wx2_test:
#  <<: *default
#  appid: "my_appid"
#  secret: "my_secret"
#
# wx2_production:
#  <<: *default
#  appid: "my_appid"
#  secret: "my_secret"
#
# wx3_development:
#  <<: *default
#  appid: "my_appid"
#  secret: "my_secret"
#  access_token: "tmp/wechat_access_token3"
#  jsapi_ticket: "tmp/wechat_jsapi_ticket3"
#
# wx3_test:
#  <<: *default
#  appid: "my_appid"
#  secret: "my_secret"
#
# wx3_production:
#  <<: *default
#  appid: "my_appid"
#  secret: "my_secret"
#
